spring.application.name=escape
#jwt.secret=${JWT_SECRET}
jwt.secret=escape-development-secret-key-123456789
spring.datasource.url=jdbc:h2:file:./data/escape-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=escape
spring.datasource.password=escape-password
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email