spring.application.name=escape
jwt.secret=${JWT_SECRET}
spring.datasource.url=jdbc:h2:file:./data/escape-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=escape
spring.datasource.password=escape-password
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update